services:
  BE:
    image: jikey002/capstone-orm:latest
    container_name: con-be-capstone-orm
    ports:
      - 3070:3069
    env_file:
      - .env
  DB:
    image: mysql:latest
    container_name: nodejs_52_mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345